### ISSUE TITLE
Denser tabs with smaller height when they fill the window height

### ISSUE THREAD

**Issue by beauweta** [tabkit/tabkit2#35]
This is a carry over from:
https://groups.google.com/forum/#!topic/tabkit-2nd-edition/NdVIqvHSUPA:

In order to see more smaller tabs rather than scroll, ... you only need to change one line in tabkit.css

``` css
#TabsToolbar[vertitabbar] .tabbrowser-tab {
  -moz-box-sizing: padding-box !important;
  min-height: 14px !important; /* <=== this used to be 27px. */
  max-height: 27px !important;
}
```

14px works fine. Maybe 10px should be the minimum.
Any hope for an entry to choose this field's value (minimum tab height) in tabkit's preferences menu?

The max-height should be kept as is.Keeping 27px max makes the tabs' height normal if you have just a few, and then they start shrinking in height if you have more and they don't fit in the window.
